version: '3.8'

services:
  arma-metrics:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/pterodactyl/volumes/35b98dbb-5f3f-40b0-9d2c-2910153bc991/profile/logs:/app/logs

  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=14d'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
    depends_on:
      - arma-metrics

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  prometheus-data:
  grafana-data: