{
 "title": "Arma Reforegr Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Players",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_players{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_ai{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_fps{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "server_veh_count{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_veh_extra_count{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Performance Stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "server_fps{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_players{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_ai{node=\"pvp-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}