global:
  scrape_interval: 2s  # Abfrageintervall für Metriken

scrape_configs:
  - job_name: 'pvp-1'
    static_configs:
      - targets: ['arma-metrics:8880']
        labels:
          environment: 'production'
          server_role: 'pvp'
          node: 'pvp-1'
